import type { Article, User } from './types';

export const allArticles: Article[] = [
  {
    id: '1',
    slug: 'tech-advancements-in-2024',
    title: 'The Future is Now: Groundbreaking Tech Advancements of 2024',
    author: 'Jane Doe',
    source: 'Tech Today',
    publishedAt: '2024-07-21',
    category: 'Technology',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'futuristic technology',
    content: `The year 2024 has been a landmark for technological innovation. From quantum computing breakthroughs to the widespread adoption of AI in daily life, the landscape of technology has shifted dramatically. This article explores the most significant advancements and their potential impact on society. Quantum computing, once a theoretical concept, has seen practical applications emerge, promising to solve complex problems previously thought unsolvable. Meanwhile, AI assistants have become more sophisticated, integrating seamlessly into our homes and workplaces, enhancing productivity and convenience.`,
    summary: 'A look at major tech innovations in 2024, including quantum computing and advanced AI, and their societal impact.',
    sentiment: 'Positive',
  },
  {
    id: '2',
    slug: 'global-economic-trends-2024',
    title: 'Navigating the Tides: Global Economic Trends in 2024',
    author: 'John Smith',
    source: 'Economics Weekly',
    publishedAt: '2024-07-20',
    category: 'Business',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'stock market',
    content: `The global economy in 2024 is a mixed bag of challenges and opportunities. While some regions are experiencing robust growth driven by the tech sector, others are grappling with inflation and supply chain disruptions. This analysis delves into the key economic indicators, market trends, and policy changes shaping the world economy. Emerging markets are showing surprising resilience, but geopolitical tensions continue to cast a shadow of uncertainty over international trade.`,
    summary: 'An analysis of 2024\'s global economy, highlighting growth in some areas, challenges like inflation elsewhere, and geopolitical uncertainty.',
    sentiment: 'Neutral',
  },
  {
    id: '3',
    slug: 'environmental-challenges-on-the-rise',
    title: 'A Planet in Peril: Environmental Challenges on the Rise',
    author: 'Emily White',
    source: 'Green World',
    publishedAt: '2024-07-19',
    category: 'Environment',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'factory pollution',
    content: `Despite increased awareness, 2024 has seen a troubling escalation in environmental crises. From record-breaking heatwaves to unprecedented biodiversity loss, the planet is sending clear signals of distress. This report highlights the most pressing environmental issues, the inadequacy of current global responses, and the urgent need for decisive action. The reliance on fossil fuels remains a primary concern, with renewable energy adoption rates falling short of the required targets to combat climate change effectively.`,
    summary: 'A report on escalating environmental crises in 2024, including extreme weather and biodiversity loss, citing insufficient global action.',
    sentiment: 'Negative',
  },
  {
    id: '4',
    slug: 'breakthroughs-in-medical-science',
    title: 'A New Era of Healing: Breakthroughs in Medical Science',
    author: 'Dr. Michael Chen',
    source: 'Journal of Medicine',
    publishedAt: '2024-07-22',
    category: 'Health',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'medical research',
    content: `Medical science has made extraordinary leaps forward in 2024. Gene-editing technologies like CRISPR are now being used to treat genetic disorders that were once considered incurable. Personalized medicine, tailored to an individual's genetic makeup, is becoming a reality, offering more effective treatments with fewer side effects. Furthermore, vaccine development has accelerated, providing new tools to combat infectious diseases. These advancements promise a healthier future for humanity.`,
    summary: 'An overview of 2024 medical breakthroughs, including gene-editing for genetic disorders and the rise of personalized medicine.',
    sentiment: 'Positive',
  },
  {
    id: '5',
    slug: 'the-renaissance-of-space-exploration',
    title: 'To the Stars: The Renaissance of Space Exploration',
    author: 'Lena Petrova',
    source: 'Cosmic Chronicles',
    publishedAt: '2024-07-18',
    category: 'Science',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'rocket launch',
    content: `A new space race is upon us, but this time it\'s a collaborative and commercial endeavor. In 2024, private companies and national space agencies are working together on ambitious missions to the Moon, Mars, and beyond. This article covers the latest rocket technologies, the establishment of lunar bases, and the search for extraterrestrial life. The renewed vigor in space exploration is not just about discovery but also about creating a multi-planetary future for humanity.`,
    summary: '2024 marks a new era in space exploration with public-private partnerships aiming for the Moon and Mars, driving new technology.',
    sentiment: 'Positive',
  },
  {
    id: '6',
    slug: 'the-evolution-of-remote-work',
    title: 'The Permanent Shift: The Evolution of Remote Work',
    author: 'David Green',
    source: 'Future of Work Magazine',
    publishedAt: '2024-07-17',
    category: 'Business',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'home office',
    content: `Remote work is no longer a temporary measure but a permanent fixture of the modern workforce. In 2024, companies are grappling with the challenges of a hybrid model, from maintaining company culture to ensuring cybersecurity. This piece examines the tools, strategies, and policies that are defining the future of work. While flexibility is a major benefit, issues of digital presenteeism and burnout are becoming more prominent, requiring new management approaches.`,
    summary: 'A look at the permanent shift to remote and hybrid work in 2024, exploring challenges in culture, security, and employee well-being.',
    sentiment: 'Neutral',
  },
  {
    id: '7',
    slug: 'ai-in-the-arts',
    title: 'Creative Code: How AI is Transforming the Art World',
    author: 'Isabella Rossi',
    source: 'Art & Design Now',
    publishedAt: '2024-07-16',
    category: 'Culture',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'abstract art',
    content: `Artificial intelligence is carving out a new frontier in the creative arts. In 2024, AI algorithms are not just tools but collaborators, generating stunning visual art, composing music, and writing poetry. This exploration delves into the world of generative art, the philosophical questions it raises about creativity and authorship, and how artists are using AI to push the boundaries of their craft. The art market is slowly beginning to recognize and value AI-generated pieces.`,
    summary: 'Exploring how AI is revolutionizing the art world in 2024, from generative visuals to musical composition, and the questions it poses.',
    sentiment: 'Positive',
  },
  {
    id: '8',
    slug: 'supply-chain-vulnerabilities-exposed',
    title: 'The Weakest Link: Global Supply Chain Vulnerabilities Exposed',
    author: 'Ken Watanabe',
    source: 'Global Trade Monitor',
    publishedAt: '2024-07-15',
    category: 'Business',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cargo ship',
    content: `The fragility of our global supply chains was once again exposed in 2024. A series of seemingly unrelated events—a shipping lane blockage, a factory fire, and a labor strike—caused a domino effect, leading to widespread shortages and price hikes. This investigative report unpacks the systemic risks in our just-in-time delivery systems and explores the push towards deglobalization and regionalized manufacturing as potential solutions. The report argues that resilience must be prioritized over efficiency.`,
    summary: 'An investigative report on how recent events exposed the fragility of global supply chains, leading to a push for more resilient, regionalized systems.',
    sentiment: 'Negative',
  },
];

export const mockUser: User = {
  name: 'Alex Ray',
  email: 'alex.ray@example.com',
  avatarUrl: 'https://placehold.co/100x100.png',
};
